CREATE TABLE Users
(
UserId INT NOT NULL AUTO_INCREMENT,
Fname VARCHAR(255) NOT NULL,
Lname VARCHAR(255) NOT NULL,
Email VARCHAR(255) NOT NULL,
UPassword VARCHAR(255) NOT NULL,
Phone VARCHAR(20),
Birthday DATE NOT NULL,
About VARCHAR(300),
PRIMARY KEY (UserId)
);
CREATE TABLE Page
(
PageId INT NOT NULL AUTO_INCREMENT,
Name VARCHAR(255) NOT NULL,
DateCreated DATE NOT NULL DEFAULT CURRENT_DATE(),
CompanyEmail VARCHAR(255) NOT NULL,
Likes INT NOT NULL DEFAULT 0,
CreatorId INT NOT NULL,
PRIMARY KEY (PageId),
FOREIGN KEY (CreatorId) REFERENCES Users(UserId)
);
CREATE TABLE Post
(
PostId INT NOT NULL AUTO_INCREMENT,
Title VARCHAR(255) NOT NULL,
Likes INT NOT NULL DEFAULT 0,
PRIMARY KEY (PostId)
);
CREATE TABLE UserPost
(
PTime DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP(),
IsCreated BIT NOT NULL,
PostId INT NOT NULL,
UserId INT NOT NULL,
PRIMARY KEY (PostId, UserId, PTime),
FOREIGN KEY (PostId) REFERENCES Post(PostId),
FOREIGN KEY (UserId) REFERENCES Users(UserId)
);
CREATE TABLE LikesPage
(
UserId INT NOT NULL,
PageId INT NOT NULL,
PRIMARY KEY (UserId, PageId),
FOREIGN KEY (UserId) REFERENCES Users(UserId),
FOREIGN KEY (PageId) REFERENCES Page(PageId)
);
CREATE TABLE Friends
(
Since DATE NOT NULL DEFAULT CURRENT_DATE(),
User1Id INT NOT NULL,
User2Id INT NOT NULL,
PRIMARY KEY (User1Id, User2Id),
FOREIGN KEY (User1Id) REFERENCES Users(UserId),
FOREIGN KEY (User2Id) REFERENCES Users(UserId)
);
CREATE TABLE Chat
(
Msg VARCHAR(255) NOT NULL,
CTime DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP(),
MsgId INT NOT NULL AUTO_INCREMENT,
SenderId INT NOT NULL,
ReceiverId INT NOT NULL,
PRIMARY KEY (MsgId),
FOREIGN KEY (SenderId) REFERENCES Users(UserId),
FOREIGN KEY (ReceiverId) REFERENCES Users(UserId)
);
CREATE TABLE PagePost
(
PTime DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP(),
IsCreated BIT NOT NULL,
PostId INT NOT NULL,
PageId INT NOT NULL,
PRIMARY KEY (PostId, PageId),
FOREIGN KEY (PostId) REFERENCES Post(PostId),
FOREIGN KEY (PageId) REFERENCES Page(PageId)
);